### ISSUE TITLE
Display QR Code when Viewing a Keyboard

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationKeyboardWeb#16]
The tK app itself should be able to scan the QR code and get the keyboard referenced.

**Comment by bknatterud** [comment]
Please verify that the QR scanner on your Android device returns a JSON string similar to this JSON when scanning the attached qr code...
http://tk.unfoldingword.org/api/v1/keyboard/1
![qr](https://cloud.githubusercontent.com/assets/1545495/8363967/49c7d9fc-1b48-11e5-9e1a-82731b11bfd8.png)

**Comment by bknatterud** [comment]
This seems to work, but one concern I have is that we can't get this QR code to scan properly with any of our Android devices at the office. We are using the same QR code scanner as what Jesse is using. So I am not sure how reliably people's devices will scan these larger codes.

I'm thinking either we break up the QR code or we accept the fact that there are devices that just can't scan these?

**Comment by jag3773** [comment]
If we break them up into 2 codes will that solve the issue?  Let's try that.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by bknatterud** [comment]
Ok, when necessary keyboards are being split into multiple QR codes...
http://tk.unfoldingword.org/qr1.png
http://tk.unfoldingword.org/qr2.png

The tK app will then handle needing to scan multiple QRs.

**Comment by bknatterud** [comment]
We actually came up with a different solution for this that allows us to pretty much always use just on QR code.

We create the QR code using the following steps
1. grab the JSON for that keyboard
2. turn the JSON into a .zip file
3. base64 encode the .zip file
4. create the QR code based on the base64 encoded .zip file.

Hopefully you are ok with this solution. I think it is good because we would rarely if ever need to have more than one QR code for a keyboard.
